services:
  db:
    container_name: database
    ports:
      - "3306:3306"
    networks:
      - my-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  app:
    container_name: myapp
    build: app
    environment:
      - DB_URL=db
    ports:
      - "81:5000"
    networks:
      - my-net
    depends_on:
      - db

networks:
  my-net:
    driver: bridge

volumes:
  db-data:
    external: true
    name: db-data